version: '2'

services:
    jenkins:
        build: ./
        expose:
            - 8080
            - 50000
        environment:
            VIRTUAL_HOST: jenkins.reactiveraven.co.uk,jenkins.reactiveraven.com,jenkins.alliterativeanimals.co.uk,jenkins.alliterativeanimals.com
            VIRTUAL_PORT: 8080
        group_add:
            - 112
        privileged: True
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./jenkins_home:/var/jenkins_home
        restart: always
        network_mode: "bridge"
        ports:
            - 50000:50000
            - 8080:8080
